//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
namespace protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private byte[] _serialized_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"serialized_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] serialized_request
    {
      get { return _serialized_request; }
      set { _serialized_request = value; }
    }
    private string _timer = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcErrorResponse")]
  public partial class RpcErrorResponse : global::ProtoBuf.IExtensible
  {
    public RpcErrorResponse() {}
    
    private string _method;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private string _text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectorInfo")]
  public partial class ConnectorInfo : global::ProtoBuf.IExtensible
  {
    public ConnectorInfo() {}
    
    private uint _ServerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private uint _PlayerCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PlayerCount
    {
      get { return _PlayerCount; }
      set { _PlayerCount = value; }
    }
    private string _TcpServerIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TcpServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TcpServerIp
    {
      get { return _TcpServerIp; }
      set { _TcpServerIp = value; }
    }
    private string _HttpServerIp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"HttpServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HttpServerIp
    {
      get { return _HttpServerIp; }
      set { _HttpServerIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectorInfoResult")]
  public partial class ConnectorInfoResult : global::ProtoBuf.IExtensible
  {
    public ConnectorInfoResult() {}
    
    private protobuf.ConnectorInfoResult.Result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protobuf.ConnectorInfoResult.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _server_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=1)]
      ERROR = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginInfo")]
  public partial class LoginInfo : global::ProtoBuf.IExtensible
  {
    public LoginInfo() {}
    
    private string _serverIp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIp
    {
      get { return _serverIp; }
      set { _serverIp = value; }
    }
    private string _gsInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gsInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gsInfo
    {
      get { return _gsInfo; }
      set { _gsInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private uint _create_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"create_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint create_time
    {
      get { return _create_time; }
      set { _create_time = value; }
    }
    private string _option = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string option
    {
      get { return _option; }
      set { _option = value; }
    }
    private uint _language = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint language
    {
      get { return _language; }
      set { _language = value; }
    }
    private string _udid = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _sessionKey = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sessionKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    
    private protobuf.LoginResult.Result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protobuf.LoginResult.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _server_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private string _sessionKey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sessionKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _errmsg = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errmsg
    {
      get { return _errmsg; }
      set { _errmsg = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVERERROR", Value=1)]
      SERVERERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USERNOTFOUND", Value=2)]
      USERNOTFOUND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTH_FAILED", Value=3)]
      AUTH_FAILED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ISONFIRE", Value=4)]
      ISONFIRE = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ping")]
  public partial class Ping : global::ProtoBuf.IExtensible
  {
    public Ping() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingResult")]
  public partial class PingResult : global::ProtoBuf.IExtensible
  {
    public PingResult() {}
    
    private uint _server_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Chat")]
  public partial class Chat : global::ProtoBuf.IExtensible
  {
    public Chat() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatResult")]
  public partial class ChatResult : global::ProtoBuf.IExtensible
  {
    public ChatResult() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBaseInfo")]
  public partial class PlayerBaseInfo : global::ProtoBuf.IExtensible
  {
    public PlayerBaseInfo() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _experience;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private uint _HP;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private uint _MP;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"MP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint MP
    {
      get { return _MP; }
      set { _MP = value; }
    }
    private uint _Rage;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"Rage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint Rage
    {
      get { return _Rage; }
      set { _Rage = value; }
    }
    private uint _maxHP;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"maxHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxHP
    {
      get { return _maxHP; }
      set { _maxHP = value; }
    }
    private uint _maxMP;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"maxMP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxMP
    {
      get { return _maxMP; }
      set { _maxMP = value; }
    }
    private uint _maxRage;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"maxRage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxRage
    {
      get { return _maxRage; }
      set { _maxRage = value; }
    }
    private uint _gender = default(uint);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private uint _modelid = default(uint);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"modelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint modelid
    {
      get { return _modelid; }
      set { _modelid = value; }
    }
    private protobuf.Transform _transform = null;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.Transform transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private uint _Strenght = default(uint);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"Strenght", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Strenght
    {
      get { return _Strenght; }
      set { _Strenght = value; }
    }
    private uint _Velocity = default(uint);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"Velocity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Velocity
    {
      get { return _Velocity; }
      set { _Velocity = value; }
    }
    private uint _Mana = default(uint);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"Mana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Mana
    {
      get { return _Mana; }
      set { _Mana = value; }
    }
    private uint _Defence = default(uint);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"Defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Defence
    {
      get { return _Defence; }
      set { _Defence = value; }
    }
    private uint _Stamina = default(uint);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"Stamina", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Stamina
    {
      get { return _Stamina; }
      set { _Stamina = value; }
    }
    private uint _ATK = default(uint);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ATK", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ATK
    {
      get { return _ATK; }
      set { _ATK = value; }
    }
    private uint _Armor = default(uint);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"Armor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Armor
    {
      get { return _Armor; }
      set { _Armor = value; }
    }
    private uint _Agility = default(uint);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"Agility", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Agility
    {
      get { return _Agility; }
      set { _Agility = value; }
    }
    private uint _Spirit = default(uint);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"Spirit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Spirit
    {
      get { return _Spirit; }
      set { _Spirit = value; }
    }
    private uint _Recovery = default(uint);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"Recovery", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Recovery
    {
      get { return _Recovery; }
      set { _Recovery = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private protobuf.PlayerBaseInfo _base;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"base", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.PlayerBaseInfo @base
    {
      get { return _base; }
      set { _base = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _X; }
      set { _X = value; }
    }
    private float _Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private float _Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _Z; }
      set { _Z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quaternion")]
  public partial class Quaternion : global::ProtoBuf.IExtensible
  {
    public Quaternion() {}
    
    private float _X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _X; }
      set { _X = value; }
    }
    private float _Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private float _Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _Z; }
      set { _Z = value; }
    }
    private float _W;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"W", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float W
    {
      get { return _W; }
      set { _W = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Transform")]
  public partial class Transform : global::ProtoBuf.IExtensible
  {
    public Transform() {}
    
    private protobuf.Vector3 _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private protobuf.Quaternion _rotation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Quaternion rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private protobuf.Vector3 _scale;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Vector3 scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}