//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: msg.proto
namespace protobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Request")]
  public partial class Request : global::ProtoBuf.IExtensible
  {
    public Request() {}
    
    private ulong _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _method;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private byte[] _serialized_request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"serialized_request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] serialized_request
    {
      get { return _serialized_request; }
      set { _serialized_request = value; }
    }
    private string _timer = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"timer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string timer
    {
      get { return _timer; }
      set { _timer = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RpcErrorResponse")]
  public partial class RpcErrorResponse : global::ProtoBuf.IExtensible
  {
    public RpcErrorResponse() {}
    
    private string _method;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"method", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string method
    {
      get { return _method; }
      set { _method = value; }
    }
    private string _text;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"text", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string text
    {
      get { return _text; }
      set { _text = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectorInfo")]
  public partial class ConnectorInfo : global::ProtoBuf.IExtensible
  {
    public ConnectorInfo() {}
    
    private uint _ServerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ServerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ServerId
    {
      get { return _ServerId; }
      set { _ServerId = value; }
    }
    private uint _PlayerCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"PlayerCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint PlayerCount
    {
      get { return _PlayerCount; }
      set { _PlayerCount = value; }
    }
    private string _TcpServerIp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"TcpServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TcpServerIp
    {
      get { return _TcpServerIp; }
      set { _TcpServerIp = value; }
    }
    private string _HttpServerIp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"HttpServerIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HttpServerIp
    {
      get { return _HttpServerIp; }
      set { _HttpServerIp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConnectorInfoResult")]
  public partial class ConnectorInfoResult : global::ProtoBuf.IExtensible
  {
    public ConnectorInfoResult() {}
    
    private protobuf.ConnectorInfoResult.Result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protobuf.ConnectorInfoResult.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _server_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ERROR", Value=1)]
      ERROR = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginInfo")]
  public partial class LoginInfo : global::ProtoBuf.IExtensible
  {
    public LoginInfo() {}
    
    private string _serverIp;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"serverIp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIp
    {
      get { return _serverIp; }
      set { _serverIp = value; }
    }
    private string _gsInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gsInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gsInfo
    {
      get { return _gsInfo; }
      set { _gsInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Login")]
  public partial class Login : global::ProtoBuf.IExtensible
  {
    public Login() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private uint _create_time = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"create_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint create_time
    {
      get { return _create_time; }
      set { _create_time = value; }
    }
    private string _option = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"option", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string option
    {
      get { return _option; }
      set { _option = value; }
    }
    private uint _language = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint language
    {
      get { return _language; }
      set { _language = value; }
    }
    private string _udid = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"udid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string udid
    {
      get { return _udid; }
      set { _udid = value; }
    }
    private string _sessionKey = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sessionKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResult")]
  public partial class LoginResult : global::ProtoBuf.IExtensible
  {
    public LoginResult() {}
    
    private protobuf.LoginResult.Result _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protobuf.LoginResult.Result result
    {
      get { return _result; }
      set { _result = value; }
    }
    private uint _server_time;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private string _sessionKey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sessionKey", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionKey
    {
      get { return _sessionKey; }
      set { _sessionKey = value; }
    }
    private string _uid;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _errmsg = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"errmsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string errmsg
    {
      get { return _errmsg; }
      set { _errmsg = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"Result")]
    public enum Result
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OK", Value=0)]
      OK = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"SERVERERROR", Value=1)]
      SERVERERROR = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"USERNOTFOUND", Value=2)]
      USERNOTFOUND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AUTH_FAILED", Value=3)]
      AUTH_FAILED = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ISONFIRE", Value=4)]
      ISONFIRE = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Ping")]
  public partial class Ping : global::ProtoBuf.IExtensible
  {
    public Ping() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PingResult")]
  public partial class PingResult : global::ProtoBuf.IExtensible
  {
    public PingResult() {}
    
    private uint _server_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"server_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint server_time
    {
      get { return _server_time; }
      set { _server_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Chat")]
  public partial class Chat : global::ProtoBuf.IExtensible
  {
    public Chat() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChatResult")]
  public partial class ChatResult : global::ProtoBuf.IExtensible
  {
    public ChatResult() {}
    
    private string _msg;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StatusInfo")]
  public partial class StatusInfo : global::ProtoBuf.IExtensible
  {
    public StatusInfo() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _experience = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"experience", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint experience
    {
      get { return _experience; }
      set { _experience = value; }
    }
    private uint _HP = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"HP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint HP
    {
      get { return _HP; }
      set { _HP = value; }
    }
    private uint _MP = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"MP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint MP
    {
      get { return _MP; }
      set { _MP = value; }
    }
    private uint _Rage = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Rage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Rage
    {
      get { return _Rage; }
      set { _Rage = value; }
    }
    private uint _gender = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"gender", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint gender
    {
      get { return _gender; }
      set { _gender = value; }
    }
    private uint _modelid = default(uint);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"modelid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint modelid
    {
      get { return _modelid; }
      set { _modelid = value; }
    }
    private protobuf.Transform _transform = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"transform", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.Transform transform
    {
      get { return _transform; }
      set { _transform = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyBaseInfo")]
  public partial class PropertyBaseInfo : global::ProtoBuf.IExtensible
  {
    public PropertyBaseInfo() {}
    
    private uint _Strenght = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Strenght", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Strenght
    {
      get { return _Strenght; }
      set { _Strenght = value; }
    }
    private uint _Velocity = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Velocity", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Velocity
    {
      get { return _Velocity; }
      set { _Velocity = value; }
    }
    private uint _Mana = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Mana", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Mana
    {
      get { return _Mana; }
      set { _Mana = value; }
    }
    private uint _Defence = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Defence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Defence
    {
      get { return _Defence; }
      set { _Defence = value; }
    }
    private uint _Stamina = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Stamina", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Stamina
    {
      get { return _Stamina; }
      set { _Stamina = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyInfo")]
  public partial class PropertyInfo : global::ProtoBuf.IExtensible
  {
    public PropertyInfo() {}
    
    private uint _maxHP = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"maxHP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxHP
    {
      get { return _maxHP; }
      set { _maxHP = value; }
    }
    private uint _maxMP = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxMP", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint maxMP
    {
      get { return _maxMP; }
      set { _maxMP = value; }
    }
    private uint _ATK = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ATK", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint ATK
    {
      get { return _ATK; }
      set { _ATK = value; }
    }
    private uint _Armor = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Armor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Armor
    {
      get { return _Armor; }
      set { _Armor = value; }
    }
    private uint _Agility = default(uint);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Agility", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Agility
    {
      get { return _Agility; }
      set { _Agility = value; }
    }
    private uint _Spirit = default(uint);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"Spirit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Spirit
    {
      get { return _Spirit; }
      set { _Spirit = value; }
    }
    private uint _Recovery = default(uint);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"Recovery", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Recovery
    {
      get { return _Recovery; }
      set { _Recovery = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyReviseInfo")]
  public partial class PropertyReviseInfo : global::ProtoBuf.IExtensible
  {
    public PropertyReviseInfo() {}
    
    private uint _UltimateKill = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"UltimateKill", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint UltimateKill
    {
      get { return _UltimateKill; }
      set { _UltimateKill = value; }
    }
    private uint _Hit = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Hit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Hit
    {
      get { return _Hit; }
      set { _Hit = value; }
    }
    private uint _CounterAttack = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"CounterAttack", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint CounterAttack
    {
      get { return _CounterAttack; }
      set { _CounterAttack = value; }
    }
    private uint _Dodge = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Dodge", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Dodge
    {
      get { return _Dodge; }
      set { _Dodge = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PropertyAgainstInfo")]
  public partial class PropertyAgainstInfo : global::ProtoBuf.IExtensible
  {
    public PropertyAgainstInfo() {}
    
    private uint _MagicAgainst = default(uint);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"MagicAgainst", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint MagicAgainst
    {
      get { return _MagicAgainst; }
      set { _MagicAgainst = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerBaseInfo")]
  public partial class PlayerBaseInfo : global::ProtoBuf.IExtensible
  {
    public PlayerBaseInfo() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private protobuf.StatusInfo _stat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.StatusInfo stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private protobuf.PropertyBaseInfo _bp = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyBaseInfo bp
    {
      get { return _bp; }
      set { _bp = value; }
    }
    private protobuf.PropertyInfo _property = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"property", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyInfo property
    {
      get { return _property; }
      set { _property = value; }
    }
    private protobuf.PropertyReviseInfo _revise = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"revise", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyReviseInfo revise
    {
      get { return _revise; }
      set { _revise = value; }
    }
    private protobuf.PropertyAgainstInfo _against = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"against", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyAgainstInfo against
    {
      get { return _against; }
      set { _against = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private protobuf.Login _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Login account
    {
      get { return _account; }
      set { _account = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector3")]
  public partial class Vector3 : global::ProtoBuf.IExtensible
  {
    public Vector3() {}
    
    private float _X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _X; }
      set { _X = value; }
    }
    private float _Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private float _Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _Z; }
      set { _Z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Quaternion")]
  public partial class Quaternion : global::ProtoBuf.IExtensible
  {
    public Quaternion() {}
    
    private float _X;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"X", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float X
    {
      get { return _X; }
      set { _X = value; }
    }
    private float _Y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Y
    {
      get { return _Y; }
      set { _Y = value; }
    }
    private float _Z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float Z
    {
      get { return _Z; }
      set { _Z = value; }
    }
    private float _W;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"W", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float W
    {
      get { return _W; }
      set { _W = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Transform")]
  public partial class Transform : global::ProtoBuf.IExtensible
  {
    public Transform() {}
    
    private protobuf.Vector3 _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Vector3 position
    {
      get { return _position; }
      set { _position = value; }
    }
    private protobuf.Quaternion _rotation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Quaternion rotation
    {
      get { return _rotation; }
      set { _rotation = value; }
    }
    private protobuf.Vector3 _scale;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"scale", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Vector3 scale
    {
      get { return _scale; }
      set { _scale = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreatureBaseInfo")]
  public partial class CreatureBaseInfo : global::ProtoBuf.IExtensible
  {
    public CreatureBaseInfo() {}
    
    private string _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private protobuf.StatusInfo _stat;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"stat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.StatusInfo stat
    {
      get { return _stat; }
      set { _stat = value; }
    }
    private protobuf.PropertyBaseInfo _bp = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"bp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyBaseInfo bp
    {
      get { return _bp; }
      set { _bp = value; }
    }
    private protobuf.PropertyInfo _property = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"property", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyInfo property
    {
      get { return _property; }
      set { _property = value; }
    }
    private protobuf.PropertyReviseInfo _revise = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"revise", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyReviseInfo revise
    {
      get { return _revise; }
      set { _revise = value; }
    }
    private protobuf.PropertyAgainstInfo _against = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"against", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PropertyAgainstInfo against
    {
      get { return _against; }
      set { _against = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttackInfo")]
  public partial class AttackInfo : global::ProtoBuf.IExtensible
  {
    public AttackInfo() {}
    
    private uint _droptime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"droptime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint droptime
    {
      get { return _droptime; }
      set { _droptime = value; }
    }
    private uint _attacker;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private uint _position;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Spell")]
  public partial class Spell : global::ProtoBuf.IExtensible
  {
    public Spell() {}
    
    private protobuf.SpellType _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public protobuf.SpellType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _level = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint level
    {
      get { return _level; }
      set { _level = value; }
    }
    private uint _damage = default(uint);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private uint _range = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint range
    {
      get { return _range; }
      set { _range = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SpellInfo")]
  public partial class SpellInfo : global::ProtoBuf.IExtensible
  {
    public SpellInfo() {}
    
    private uint _droptime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"droptime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint droptime
    {
      get { return _droptime; }
      set { _droptime = value; }
    }
    private uint _attacker;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"attacker", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint attacker
    {
      get { return _attacker; }
      set { _attacker = value; }
    }
    private uint _position;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint position
    {
      get { return _position; }
      set { _position = value; }
    }
    private protobuf.Spell _spell;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"spell", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public protobuf.Spell spell
    {
      get { return _spell; }
      set { _spell = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleTest")]
  public partial class BattleTest : global::ProtoBuf.IExtensible
  {
    public BattleTest() {}
    
    private readonly global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> _enemy = new global::System.Collections.Generic.List<protobuf.CreatureBaseInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"enemy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> enemy
    {
      get { return _enemy; }
    }
  
    private protobuf.PlayerBaseInfo _player = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"player", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protobuf.PlayerBaseInfo player
    {
      get { return _player; }
      set { _player = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleInfo")]
  public partial class BattleInfo : global::ProtoBuf.IExtensible
  {
    public BattleInfo() {}
    
    private string _bid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bid
    {
      get { return _bid; }
      set { _bid = value; }
    }
    private readonly global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> _partner = new global::System.Collections.Generic.List<protobuf.CreatureBaseInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"partner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> partner
    {
      get { return _partner; }
    }
  
    private readonly global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> _enemy = new global::System.Collections.Generic.List<protobuf.CreatureBaseInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"enemy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> enemy
    {
      get { return _enemy; }
    }
  
    private readonly global::System.Collections.Generic.List<protobuf.AttackInfo> _attackunits = new global::System.Collections.Generic.List<protobuf.AttackInfo>();
    [global::ProtoBuf.ProtoMember(4, Name=@"attackunits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.AttackInfo> attackunits
    {
      get { return _attackunits; }
    }
  
    private readonly global::System.Collections.Generic.List<protobuf.SpellInfo> _spells = new global::System.Collections.Generic.List<protobuf.SpellInfo>();
    [global::ProtoBuf.ProtoMember(5, Name=@"spells", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.SpellInfo> spells
    {
      get { return _spells; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyBattleStart")]
  public partial class NotifyBattleStart : global::ProtoBuf.IExtensible
  {
    public NotifyBattleStart() {}
    
    private string _bid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bid
    {
      get { return _bid; }
      set { _bid = value; }
    }
    private readonly global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> _partner = new global::System.Collections.Generic.List<protobuf.CreatureBaseInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"partner", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> partner
    {
      get { return _partner; }
    }
  
    private readonly global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> _enemy = new global::System.Collections.Generic.List<protobuf.CreatureBaseInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"enemy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.CreatureBaseInfo> enemy
    {
      get { return _enemy; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BattleAttackQueue")]
  public partial class BattleAttackQueue : global::ProtoBuf.IExtensible
  {
    public BattleAttackQueue() {}
    
    private string _bid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string bid
    {
      get { return _bid; }
      set { _bid = value; }
    }
    private readonly global::System.Collections.Generic.List<protobuf.AttackInfo> _attackunits = new global::System.Collections.Generic.List<protobuf.AttackInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attackunits", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.AttackInfo> attackunits
    {
      get { return _attackunits; }
    }
  
    private readonly global::System.Collections.Generic.List<protobuf.SpellInfo> _spells = new global::System.Collections.Generic.List<protobuf.SpellInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"spells", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<protobuf.SpellInfo> spells
    {
      get { return _spells; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NotifyBattleEnd")]
  public partial class NotifyBattleEnd : global::ProtoBuf.IExtensible
  {
    public NotifyBattleEnd() {}
    
    private string _playerlid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerlid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string playerlid
    {
      get { return _playerlid; }
      set { _playerlid = value; }
    }
    private uint _exp = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint exp
    {
      get { return _exp; }
      set { _exp = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"SpellType")]
    public enum SpellType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"LighningStorm", Value=1)]
      LighningStorm = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HealingWave", Value=2)]
      HealingWave = 2
    }
  
}