-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local PB_PacketDefine_pb = require("PB_PacketDefine_pb")
module('CSPacket_pb')


local CS_CHECKSESSION = protobuf.Descriptor();
local CS_CHECKSESSION_UID_FIELD = protobuf.FieldDescriptor();
local CS_CHECKSESSION_SESSIONKEY_FIELD = protobuf.FieldDescriptor();
local CS_CHECKSESSION_TIMESTAMP_FIELD = protobuf.FieldDescriptor();
local CS_PING = protobuf.Descriptor();
local CS_LEAVECLIENTSCENE = protobuf.Descriptor();
local CS_ENTERFIGHT = protobuf.Descriptor();
local CS_LEAVEFIGHT = protobuf.Descriptor();
local CS_LEAVEFIGHT_ROUNDID_FIELD = protobuf.FieldDescriptor();
local CS_BATTLEROUNDINFO = protobuf.Descriptor();
local CS_BATTLEROUNDINFO_ROUNDID_FIELD = protobuf.FieldDescriptor();

CS_CHECKSESSION_UID_FIELD.name = "uid"
CS_CHECKSESSION_UID_FIELD.full_name = ".protobuf.CS_CheckSession.uid"
CS_CHECKSESSION_UID_FIELD.number = 1
CS_CHECKSESSION_UID_FIELD.index = 0
CS_CHECKSESSION_UID_FIELD.label = 2
CS_CHECKSESSION_UID_FIELD.has_default_value = false
CS_CHECKSESSION_UID_FIELD.default_value = ""
CS_CHECKSESSION_UID_FIELD.type = 9
CS_CHECKSESSION_UID_FIELD.cpp_type = 9

CS_CHECKSESSION_SESSIONKEY_FIELD.name = "sessionKey"
CS_CHECKSESSION_SESSIONKEY_FIELD.full_name = ".protobuf.CS_CheckSession.sessionKey"
CS_CHECKSESSION_SESSIONKEY_FIELD.number = 2
CS_CHECKSESSION_SESSIONKEY_FIELD.index = 1
CS_CHECKSESSION_SESSIONKEY_FIELD.label = 2
CS_CHECKSESSION_SESSIONKEY_FIELD.has_default_value = false
CS_CHECKSESSION_SESSIONKEY_FIELD.default_value = ""
CS_CHECKSESSION_SESSIONKEY_FIELD.type = 9
CS_CHECKSESSION_SESSIONKEY_FIELD.cpp_type = 9

CS_CHECKSESSION_TIMESTAMP_FIELD.name = "timestamp"
CS_CHECKSESSION_TIMESTAMP_FIELD.full_name = ".protobuf.CS_CheckSession.timestamp"
CS_CHECKSESSION_TIMESTAMP_FIELD.number = 3
CS_CHECKSESSION_TIMESTAMP_FIELD.index = 2
CS_CHECKSESSION_TIMESTAMP_FIELD.label = 1
CS_CHECKSESSION_TIMESTAMP_FIELD.has_default_value = false
CS_CHECKSESSION_TIMESTAMP_FIELD.default_value = 0
CS_CHECKSESSION_TIMESTAMP_FIELD.type = 13
CS_CHECKSESSION_TIMESTAMP_FIELD.cpp_type = 3

CS_CHECKSESSION.name = "CS_CheckSession"
CS_CHECKSESSION.full_name = ".protobuf.CS_CheckSession"
CS_CHECKSESSION.nested_types = {}
CS_CHECKSESSION.enum_types = {}
CS_CHECKSESSION.fields = {CS_CHECKSESSION_UID_FIELD, CS_CHECKSESSION_SESSIONKEY_FIELD, CS_CHECKSESSION_TIMESTAMP_FIELD}
CS_CHECKSESSION.is_extendable = false
CS_CHECKSESSION.extensions = {}
CS_PING.name = "CS_Ping"
CS_PING.full_name = ".protobuf.CS_Ping"
CS_PING.nested_types = {}
CS_PING.enum_types = {}
CS_PING.fields = {}
CS_PING.is_extendable = false
CS_PING.extensions = {}
CS_LEAVECLIENTSCENE.name = "CS_LeaveClientScene"
CS_LEAVECLIENTSCENE.full_name = ".protobuf.CS_LeaveClientScene"
CS_LEAVECLIENTSCENE.nested_types = {}
CS_LEAVECLIENTSCENE.enum_types = {}
CS_LEAVECLIENTSCENE.fields = {}
CS_LEAVECLIENTSCENE.is_extendable = false
CS_LEAVECLIENTSCENE.extensions = {}
CS_ENTERFIGHT.name = "CS_EnterFight"
CS_ENTERFIGHT.full_name = ".protobuf.CS_EnterFight"
CS_ENTERFIGHT.nested_types = {}
CS_ENTERFIGHT.enum_types = {}
CS_ENTERFIGHT.fields = {}
CS_ENTERFIGHT.is_extendable = false
CS_ENTERFIGHT.extensions = {}
CS_LEAVEFIGHT_ROUNDID_FIELD.name = "RoundId"
CS_LEAVEFIGHT_ROUNDID_FIELD.full_name = ".protobuf.CS_LeaveFight.RoundId"
CS_LEAVEFIGHT_ROUNDID_FIELD.number = 1
CS_LEAVEFIGHT_ROUNDID_FIELD.index = 0
CS_LEAVEFIGHT_ROUNDID_FIELD.label = 2
CS_LEAVEFIGHT_ROUNDID_FIELD.has_default_value = false
CS_LEAVEFIGHT_ROUNDID_FIELD.default_value = 0
CS_LEAVEFIGHT_ROUNDID_FIELD.type = 13
CS_LEAVEFIGHT_ROUNDID_FIELD.cpp_type = 3

CS_LEAVEFIGHT.name = "CS_LeaveFight"
CS_LEAVEFIGHT.full_name = ".protobuf.CS_LeaveFight"
CS_LEAVEFIGHT.nested_types = {}
CS_LEAVEFIGHT.enum_types = {}
CS_LEAVEFIGHT.fields = {CS_LEAVEFIGHT_ROUNDID_FIELD}
CS_LEAVEFIGHT.is_extendable = false
CS_LEAVEFIGHT.extensions = {}
CS_BATTLEROUNDINFO_ROUNDID_FIELD.name = "RoundId"
CS_BATTLEROUNDINFO_ROUNDID_FIELD.full_name = ".protobuf.CS_BattleRoundInfo.RoundId"
CS_BATTLEROUNDINFO_ROUNDID_FIELD.number = 1
CS_BATTLEROUNDINFO_ROUNDID_FIELD.index = 0
CS_BATTLEROUNDINFO_ROUNDID_FIELD.label = 2
CS_BATTLEROUNDINFO_ROUNDID_FIELD.has_default_value = false
CS_BATTLEROUNDINFO_ROUNDID_FIELD.default_value = 0
CS_BATTLEROUNDINFO_ROUNDID_FIELD.type = 13
CS_BATTLEROUNDINFO_ROUNDID_FIELD.cpp_type = 3

CS_BATTLEROUNDINFO.name = "CS_BattleRoundInfo"
CS_BATTLEROUNDINFO.full_name = ".protobuf.CS_BattleRoundInfo"
CS_BATTLEROUNDINFO.nested_types = {}
CS_BATTLEROUNDINFO.enum_types = {}
CS_BATTLEROUNDINFO.fields = {CS_BATTLEROUNDINFO_ROUNDID_FIELD}
CS_BATTLEROUNDINFO.is_extendable = false
CS_BATTLEROUNDINFO.extensions = {}

CS_BattleRoundInfo = protobuf.Message(CS_BATTLEROUNDINFO)
CS_CheckSession = protobuf.Message(CS_CHECKSESSION)
CS_EnterFight = protobuf.Message(CS_ENTERFIGHT)
CS_LeaveClientScene = protobuf.Message(CS_LEAVECLIENTSCENE)
CS_LeaveFight = protobuf.Message(CS_LEAVEFIGHT)
CS_Ping = protobuf.Message(CS_PING)

