-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local PB_PacketDefine_pb = require("PB_PacketDefine_pb")
module('CSPacket_pb')


local CS_CHECKSESSION = protobuf.Descriptor();
local CS_CHECKSESSION_UID_FIELD = protobuf.FieldDescriptor();
local CS_CHECKSESSION_SESSIONKEY_FIELD = protobuf.FieldDescriptor();
local CS_CHECKSESSION_CREATE_TIME_FIELD = protobuf.FieldDescriptor();
local CS_PING = protobuf.Descriptor();

CS_CHECKSESSION_UID_FIELD.name = "uid"
CS_CHECKSESSION_UID_FIELD.full_name = ".protobuf.CS_CheckSession.uid"
CS_CHECKSESSION_UID_FIELD.number = 1
CS_CHECKSESSION_UID_FIELD.index = 0
CS_CHECKSESSION_UID_FIELD.label = 2
CS_CHECKSESSION_UID_FIELD.has_default_value = false
CS_CHECKSESSION_UID_FIELD.default_value = ""
CS_CHECKSESSION_UID_FIELD.type = 9
CS_CHECKSESSION_UID_FIELD.cpp_type = 9

CS_CHECKSESSION_SESSIONKEY_FIELD.name = "sessionKey"
CS_CHECKSESSION_SESSIONKEY_FIELD.full_name = ".protobuf.CS_CheckSession.sessionKey"
CS_CHECKSESSION_SESSIONKEY_FIELD.number = 2
CS_CHECKSESSION_SESSIONKEY_FIELD.index = 1
CS_CHECKSESSION_SESSIONKEY_FIELD.label = 2
CS_CHECKSESSION_SESSIONKEY_FIELD.has_default_value = false
CS_CHECKSESSION_SESSIONKEY_FIELD.default_value = ""
CS_CHECKSESSION_SESSIONKEY_FIELD.type = 9
CS_CHECKSESSION_SESSIONKEY_FIELD.cpp_type = 9

CS_CHECKSESSION_CREATE_TIME_FIELD.name = "create_time"
CS_CHECKSESSION_CREATE_TIME_FIELD.full_name = ".protobuf.CS_CheckSession.create_time"
CS_CHECKSESSION_CREATE_TIME_FIELD.number = 3
CS_CHECKSESSION_CREATE_TIME_FIELD.index = 2
CS_CHECKSESSION_CREATE_TIME_FIELD.label = 1
CS_CHECKSESSION_CREATE_TIME_FIELD.has_default_value = false
CS_CHECKSESSION_CREATE_TIME_FIELD.default_value = 0
CS_CHECKSESSION_CREATE_TIME_FIELD.type = 13
CS_CHECKSESSION_CREATE_TIME_FIELD.cpp_type = 3

CS_CHECKSESSION.name = "CS_CheckSession"
CS_CHECKSESSION.full_name = ".protobuf.CS_CheckSession"
CS_CHECKSESSION.nested_types = {}
CS_CHECKSESSION.enum_types = {}
CS_CHECKSESSION.fields = {CS_CHECKSESSION_UID_FIELD, CS_CHECKSESSION_SESSIONKEY_FIELD, CS_CHECKSESSION_CREATE_TIME_FIELD}
CS_CHECKSESSION.is_extendable = false
CS_CHECKSESSION.extensions = {}
CS_PING.name = "CS_Ping"
CS_PING.full_name = ".protobuf.CS_Ping"
CS_PING.nested_types = {}
CS_PING.enum_types = {}
CS_PING.fields = {}
CS_PING.is_extendable = false
CS_PING.extensions = {}

CS_CheckSession = protobuf.Message(CS_CHECKSESSION)
CS_Ping = protobuf.Message(CS_PING)

