-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
local PB_PacketServerDefine_pb = require("PB_PacketServerDefine_pb")
module('SFPacket_pb')


local SF_BATTLE = protobuf.Descriptor();
local SF_ENTERBATTLE = protobuf.Descriptor();
local SF_EXITBATTLE = protobuf.Descriptor();
local SF_BATTLEQUERY = protobuf.Descriptor();

SF_BATTLE.name = "SF_Battle"
SF_BATTLE.full_name = ".protobuf.SF_Battle"
SF_BATTLE.nested_types = {}
SF_BATTLE.enum_types = {}
SF_BATTLE.fields = {}
SF_BATTLE.is_extendable = false
SF_BATTLE.extensions = {}
SF_ENTERBATTLE.name = "SF_EnterBattle"
SF_ENTERBATTLE.full_name = ".protobuf.SF_EnterBattle"
SF_ENTERBATTLE.nested_types = {}
SF_ENTERBATTLE.enum_types = {}
SF_ENTERBATTLE.fields = {}
SF_ENTERBATTLE.is_extendable = false
SF_ENTERBATTLE.extensions = {}
SF_EXITBATTLE.name = "SF_ExitBattle"
SF_EXITBATTLE.full_name = ".protobuf.SF_ExitBattle"
SF_EXITBATTLE.nested_types = {}
SF_EXITBATTLE.enum_types = {}
SF_EXITBATTLE.fields = {}
SF_EXITBATTLE.is_extendable = false
SF_EXITBATTLE.extensions = {}
SF_BATTLEQUERY.name = "SF_BattleQuery"
SF_BATTLEQUERY.full_name = ".protobuf.SF_BattleQuery"
SF_BATTLEQUERY.nested_types = {}
SF_BATTLEQUERY.enum_types = {}
SF_BATTLEQUERY.fields = {}
SF_BATTLEQUERY.is_extendable = false
SF_BATTLEQUERY.extensions = {}

SF_Battle = protobuf.Message(SF_BATTLE)
SF_BattleQuery = protobuf.Message(SF_BATTLEQUERY)
SF_EnterBattle = protobuf.Message(SF_ENTERBATTLE)
SF_ExitBattle = protobuf.Message(SF_EXITBATTLE)

