-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('XShare_Logic_pb')


local PLAYERINFO = protobuf.Descriptor();
local PLAYERINFO_UID_FIELD = protobuf.FieldDescriptor();
local PLAYERINFO_STAT_FIELD = protobuf.FieldDescriptor();
local PLAYERINFO_BP_FIELD = protobuf.FieldDescriptor();
local PLAYERINFO_PROPERTY_FIELD = protobuf.FieldDescriptor();
local PLAYERINFO_REVISE_FIELD = protobuf.FieldDescriptor();
local PLAYERINFO_AGAINST_FIELD = protobuf.FieldDescriptor();

PLAYERINFO_UID_FIELD.name = "uid"
PLAYERINFO_UID_FIELD.full_name = ".protobuf.PlayerInfo.uid"
PLAYERINFO_UID_FIELD.number = 1
PLAYERINFO_UID_FIELD.index = 0
PLAYERINFO_UID_FIELD.label = 2
PLAYERINFO_UID_FIELD.has_default_value = false
PLAYERINFO_UID_FIELD.default_value = ""
PLAYERINFO_UID_FIELD.type = 9
PLAYERINFO_UID_FIELD.cpp_type = 9

PLAYERINFO_STAT_FIELD.name = "stat"
PLAYERINFO_STAT_FIELD.full_name = ".protobuf.PlayerInfo.stat"
PLAYERINFO_STAT_FIELD.number = 2
PLAYERINFO_STAT_FIELD.index = 1
PLAYERINFO_STAT_FIELD.label = 2
PLAYERINFO_STAT_FIELD.has_default_value = false
PLAYERINFO_STAT_FIELD.default_value = ""
PLAYERINFO_STAT_FIELD.type = 12
PLAYERINFO_STAT_FIELD.cpp_type = 9

PLAYERINFO_BP_FIELD.name = "bp"
PLAYERINFO_BP_FIELD.full_name = ".protobuf.PlayerInfo.bp"
PLAYERINFO_BP_FIELD.number = 3
PLAYERINFO_BP_FIELD.index = 2
PLAYERINFO_BP_FIELD.label = 1
PLAYERINFO_BP_FIELD.has_default_value = false
PLAYERINFO_BP_FIELD.default_value = ""
PLAYERINFO_BP_FIELD.type = 12
PLAYERINFO_BP_FIELD.cpp_type = 9

PLAYERINFO_PROPERTY_FIELD.name = "property"
PLAYERINFO_PROPERTY_FIELD.full_name = ".protobuf.PlayerInfo.property"
PLAYERINFO_PROPERTY_FIELD.number = 4
PLAYERINFO_PROPERTY_FIELD.index = 3
PLAYERINFO_PROPERTY_FIELD.label = 1
PLAYERINFO_PROPERTY_FIELD.has_default_value = false
PLAYERINFO_PROPERTY_FIELD.default_value = ""
PLAYERINFO_PROPERTY_FIELD.type = 12
PLAYERINFO_PROPERTY_FIELD.cpp_type = 9

PLAYERINFO_REVISE_FIELD.name = "revise"
PLAYERINFO_REVISE_FIELD.full_name = ".protobuf.PlayerInfo.revise"
PLAYERINFO_REVISE_FIELD.number = 5
PLAYERINFO_REVISE_FIELD.index = 4
PLAYERINFO_REVISE_FIELD.label = 1
PLAYERINFO_REVISE_FIELD.has_default_value = false
PLAYERINFO_REVISE_FIELD.default_value = ""
PLAYERINFO_REVISE_FIELD.type = 12
PLAYERINFO_REVISE_FIELD.cpp_type = 9

PLAYERINFO_AGAINST_FIELD.name = "against"
PLAYERINFO_AGAINST_FIELD.full_name = ".protobuf.PlayerInfo.against"
PLAYERINFO_AGAINST_FIELD.number = 6
PLAYERINFO_AGAINST_FIELD.index = 5
PLAYERINFO_AGAINST_FIELD.label = 1
PLAYERINFO_AGAINST_FIELD.has_default_value = false
PLAYERINFO_AGAINST_FIELD.default_value = ""
PLAYERINFO_AGAINST_FIELD.type = 12
PLAYERINFO_AGAINST_FIELD.cpp_type = 9

PLAYERINFO.name = "PlayerInfo"
PLAYERINFO.full_name = ".protobuf.PlayerInfo"
PLAYERINFO.nested_types = {}
PLAYERINFO.enum_types = {}
PLAYERINFO.fields = {PLAYERINFO_UID_FIELD, PLAYERINFO_STAT_FIELD, PLAYERINFO_BP_FIELD, PLAYERINFO_PROPERTY_FIELD, PLAYERINFO_REVISE_FIELD, PLAYERINFO_AGAINST_FIELD}
PLAYERINFO.is_extendable = false
PLAYERINFO.extensions = {}

PlayerInfo = protobuf.Message(PLAYERINFO)

