// Code generated by protoc-gen-go.
// source: FSPacket.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	FSPacket.proto

It has these top-level messages:
	FS_Battle
	FS_BattleBegin
	FS_BattleEnd
	FS_BattleInfo
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import protobuf1 "PB_PacketServerDefine.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FS_Battle struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FS_Battle) Reset()         { *m = FS_Battle{} }
func (m *FS_Battle) String() string { return proto.CompactTextString(m) }
func (*FS_Battle) ProtoMessage()    {}

type FS_BattleBegin struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FS_BattleBegin) Reset()         { *m = FS_BattleBegin{} }
func (m *FS_BattleBegin) String() string { return proto.CompactTextString(m) }
func (*FS_BattleBegin) ProtoMessage()    {}

type FS_BattleEnd struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FS_BattleEnd) Reset()         { *m = FS_BattleEnd{} }
func (m *FS_BattleEnd) String() string { return proto.CompactTextString(m) }
func (*FS_BattleEnd) ProtoMessage()    {}

type FS_BattleInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *FS_BattleInfo) Reset()         { *m = FS_BattleInfo{} }
func (m *FS_BattleInfo) String() string { return proto.CompactTextString(m) }
func (*FS_BattleInfo) ProtoMessage()    {}

func init() {
}
