// Code generated by protoc-gen-go.
// source: LSPacket.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	LSPacket.proto

It has these top-level messages:
	LS_UpdatePlayerCountResult
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// discarding unused import protobuf1 "PB_PacketServerDefine.pb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LS_UpdatePlayerCountResult_Result int32

const (
	LS_UpdatePlayerCountResult_OK          LS_UpdatePlayerCountResult_Result = 0
	LS_UpdatePlayerCountResult_SERVERERROR LS_UpdatePlayerCountResult_Result = 1
)

var LS_UpdatePlayerCountResult_Result_name = map[int32]string{
	0: "OK",
	1: "SERVERERROR",
}
var LS_UpdatePlayerCountResult_Result_value = map[string]int32{
	"OK":          0,
	"SERVERERROR": 1,
}

func (x LS_UpdatePlayerCountResult_Result) Enum() *LS_UpdatePlayerCountResult_Result {
	p := new(LS_UpdatePlayerCountResult_Result)
	*p = x
	return p
}
func (x LS_UpdatePlayerCountResult_Result) String() string {
	return proto.EnumName(LS_UpdatePlayerCountResult_Result_name, int32(x))
}
func (x LS_UpdatePlayerCountResult_Result) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *LS_UpdatePlayerCountResult_Result) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LS_UpdatePlayerCountResult_Result_value, data, "LS_UpdatePlayerCountResult_Result")
	if err != nil {
		return err
	}
	*x = LS_UpdatePlayerCountResult_Result(value)
	return nil
}

type LS_UpdatePlayerCountResult struct {
	Result           *LS_UpdatePlayerCountResult_Result `protobuf:"varint,1,req,name=result,enum=protobuf.LS_UpdatePlayerCountResult_Result,def=0" json:"result,omitempty"`
	ServerTime       *uint32                            `protobuf:"varint,2,req,name=server_time" json:"server_time,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *LS_UpdatePlayerCountResult) Reset()         { *m = LS_UpdatePlayerCountResult{} }
func (m *LS_UpdatePlayerCountResult) String() string { return proto.CompactTextString(m) }
func (*LS_UpdatePlayerCountResult) ProtoMessage()    {}

const Default_LS_UpdatePlayerCountResult_Result LS_UpdatePlayerCountResult_Result = LS_UpdatePlayerCountResult_OK

func (m *LS_UpdatePlayerCountResult) GetResult() LS_UpdatePlayerCountResult_Result {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return Default_LS_UpdatePlayerCountResult_Result
}

func (m *LS_UpdatePlayerCountResult) GetServerTime() uint32 {
	if m != nil && m.ServerTime != nil {
		return *m.ServerTime
	}
	return 0
}

func (m *LS_UpdatePlayerCountResult) SetResult(value LS_UpdatePlayerCountResult_Result) {
	if m != nil {
		m.Result = &value
	}
}

func (m *LS_UpdatePlayerCountResult) SetServerTime(value uint32) {
	if m != nil {
		m.ServerTime = &value
	}
}

func init() {
	proto.RegisterEnum("protobuf.LS_UpdatePlayerCountResult_Result", LS_UpdatePlayerCountResult_Result_name, LS_UpdatePlayerCountResult_Result_value)
}
