// Code generated by protoc-gen-go.
// source: PB_PacketServerDefine.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	PB_PacketServerDefine.proto

It has these top-level messages:
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SL_Protocol int32

const (
	SL_Protocol_eSL_PacketBegin SL_Protocol = 12000
	// ----------------------------
	SL_Protocol_eSL_Connected         SL_Protocol = 12000
	SL_Protocol_eSL_Disconnected      SL_Protocol = 12001
	SL_Protocol_eSL_UpdatePlayerCount SL_Protocol = 12002
	// ----------------------------
	SL_Protocol_eSL_PacketEnd SL_Protocol = 20000
)

var SL_Protocol_name = map[int32]string{
	12000: "eSL_PacketBegin",
	// Duplicate value: 12000: "eSL_Connected",
	12001: "eSL_Disconnected",
	12002: "eSL_UpdatePlayerCount",
	20000: "eSL_PacketEnd",
}
var SL_Protocol_value = map[string]int32{
	"eSL_PacketBegin":       12000,
	"eSL_Connected":         12000,
	"eSL_Disconnected":      12001,
	"eSL_UpdatePlayerCount": 12002,
	"eSL_PacketEnd":         20000,
}

func (x SL_Protocol) Enum() *SL_Protocol {
	p := new(SL_Protocol)
	*p = x
	return p
}
func (x SL_Protocol) String() string {
	return proto.EnumName(SL_Protocol_name, int32(x))
}
func (x SL_Protocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *SL_Protocol) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SL_Protocol_value, data, "SL_Protocol")
	if err != nil {
		return err
	}
	*x = SL_Protocol(value)
	return nil
}

type LA_Protocol int32

const (
	LA_Protocol_eLA_PacketBegin LA_Protocol = 11000
	// ----------------------------
	LA_Protocol_eLA_Connected    LA_Protocol = 11000
	LA_Protocol_eLA_Disconnected LA_Protocol = 11001
	LA_Protocol_eLA_CheckAccount LA_Protocol = 11002
	// ----------------------------
	LA_Protocol_eLA_PacketEnd LA_Protocol = 12000
)

var LA_Protocol_name = map[int32]string{
	11000: "eLA_PacketBegin",
	// Duplicate value: 11000: "eLA_Connected",
	11001: "eLA_Disconnected",
	11002: "eLA_CheckAccount",
	12000: "eLA_PacketEnd",
}
var LA_Protocol_value = map[string]int32{
	"eLA_PacketBegin":  11000,
	"eLA_Connected":    11000,
	"eLA_Disconnected": 11001,
	"eLA_CheckAccount": 11002,
	"eLA_PacketEnd":    12000,
}

func (x LA_Protocol) Enum() *LA_Protocol {
	p := new(LA_Protocol)
	*p = x
	return p
}
func (x LA_Protocol) String() string {
	return proto.EnumName(LA_Protocol_name, int32(x))
}
func (x LA_Protocol) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *LA_Protocol) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(LA_Protocol_value, data, "LA_Protocol")
	if err != nil {
		return err
	}
	*x = LA_Protocol(value)
	return nil
}

func init() {
	proto.RegisterEnum("protobuf.SL_Protocol", SL_Protocol_name, SL_Protocol_value)
	proto.RegisterEnum("protobuf.LA_Protocol", LA_Protocol_name, LA_Protocol_value)
}
