// Code generated by protoc-gen-go.
// source: XShare_Logic.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	XShare_Logic.proto

It has these top-level messages:
	PlayerInfo
	MapPropertie
	Tileset
	MapObject
	TileLayer
	TileMap
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type PlayerInfo struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Stat             []byte  `protobuf:"bytes,2,req,name=stat" json:"stat,omitempty"`
	Bp               []byte  `protobuf:"bytes,3,opt,name=bp" json:"bp,omitempty"`
	Property         []byte  `protobuf:"bytes,4,opt,name=property" json:"property,omitempty"`
	Revise           []byte  `protobuf:"bytes,5,opt,name=revise" json:"revise,omitempty"`
	Against          []byte  `protobuf:"bytes,6,opt,name=against" json:"against,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}

func (m *PlayerInfo) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *PlayerInfo) GetStat() []byte {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *PlayerInfo) GetBp() []byte {
	if m != nil {
		return m.Bp
	}
	return nil
}

func (m *PlayerInfo) GetProperty() []byte {
	if m != nil {
		return m.Property
	}
	return nil
}

func (m *PlayerInfo) GetRevise() []byte {
	if m != nil {
		return m.Revise
	}
	return nil
}

func (m *PlayerInfo) GetAgainst() []byte {
	if m != nil {
		return m.Against
	}
	return nil
}

func (m *PlayerInfo) SetUid(value string) {
	if m != nil {
		m.Uid = &value
	}
}

func (m *PlayerInfo) SetStat(value []byte) {
	if m != nil {
		m.Stat = value
	}
}

func (m *PlayerInfo) SetBp(value []byte) {
	if m != nil {
		m.Bp = value
	}
}

func (m *PlayerInfo) SetProperty(value []byte) {
	if m != nil {
		m.Property = value
	}
}

func (m *PlayerInfo) SetRevise(value []byte) {
	if m != nil {
		m.Revise = value
	}
}

func (m *PlayerInfo) SetAgainst(value []byte) {
	if m != nil {
		m.Against = value
	}
}

// 地图自定义属性结构
type MapPropertie struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MapPropertie) Reset()         { *m = MapPropertie{} }
func (m *MapPropertie) String() string { return proto.CompactTextString(m) }
func (*MapPropertie) ProtoMessage()    {}

func (m *MapPropertie) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MapPropertie) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func (m *MapPropertie) SetName(value string) {
	if m != nil {
		m.Name = &value
	}
}

func (m *MapPropertie) SetValue(value string) {
	if m != nil {
		m.Value = &value
	}
}

// 地图地形图片结构
type Tileset struct {
	Tilewidth        *uint32 `protobuf:"varint,1,req,name=tilewidth" json:"tilewidth,omitempty"`
	Tileheight       *uint32 `protobuf:"varint,2,req,name=tileheight" json:"tileheight,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Image            *string `protobuf:"bytes,4,opt,name=image" json:"image,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Tileset) Reset()         { *m = Tileset{} }
func (m *Tileset) String() string { return proto.CompactTextString(m) }
func (*Tileset) ProtoMessage()    {}

func (m *Tileset) GetTilewidth() uint32 {
	if m != nil && m.Tilewidth != nil {
		return *m.Tilewidth
	}
	return 0
}

func (m *Tileset) GetTileheight() uint32 {
	if m != nil && m.Tileheight != nil {
		return *m.Tileheight
	}
	return 0
}

func (m *Tileset) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Tileset) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

func (m *Tileset) SetTilewidth(value uint32) {
	if m != nil {
		m.Tilewidth = &value
	}
}

func (m *Tileset) SetTileheight(value uint32) {
	if m != nil {
		m.Tileheight = &value
	}
}

func (m *Tileset) SetName(value string) {
	if m != nil {
		m.Name = &value
	}
}

func (m *Tileset) SetImage(value string) {
	if m != nil {
		m.Image = &value
	}
}

// 地图对象结构
type MapObject struct {
	Gid              *uint32  `protobuf:"varint,1,req,name=gid" json:"gid,omitempty"`
	X                *uint32  `protobuf:"varint,2,req,name=x" json:"x,omitempty"`
	Y                *uint32  `protobuf:"varint,3,req,name=y" json:"y,omitempty"`
	Width            *uint32  `protobuf:"varint,4,req,name=width" json:"width,omitempty"`
	Height           *uint32  `protobuf:"varint,5,req,name=height" json:"height,omitempty"`
	Properties       [][]byte `protobuf:"bytes,6,rep,name=properties" json:"properties,omitempty"`
	Name             *string  `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	Type             *string  `protobuf:"bytes,8,opt,name=type" json:"type,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *MapObject) Reset()         { *m = MapObject{} }
func (m *MapObject) String() string { return proto.CompactTextString(m) }
func (*MapObject) ProtoMessage()    {}

func (m *MapObject) GetGid() uint32 {
	if m != nil && m.Gid != nil {
		return *m.Gid
	}
	return 0
}

func (m *MapObject) GetX() uint32 {
	if m != nil && m.X != nil {
		return *m.X
	}
	return 0
}

func (m *MapObject) GetY() uint32 {
	if m != nil && m.Y != nil {
		return *m.Y
	}
	return 0
}

func (m *MapObject) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *MapObject) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *MapObject) GetProperties() [][]byte {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *MapObject) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *MapObject) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *MapObject) SetGid(value uint32) {
	if m != nil {
		m.Gid = &value
	}
}

func (m *MapObject) SetX(value uint32) {
	if m != nil {
		m.X = &value
	}
}

func (m *MapObject) SetY(value uint32) {
	if m != nil {
		m.Y = &value
	}
}

func (m *MapObject) SetWidth(value uint32) {
	if m != nil {
		m.Width = &value
	}
}

func (m *MapObject) SetHeight(value uint32) {
	if m != nil {
		m.Height = &value
	}
}

func (m *MapObject) SetProperties(value [][]byte) {
	if m != nil {
		m.Properties = value
	}
}

func (m *MapObject) SetName(value string) {
	if m != nil {
		m.Name = &value
	}
}

func (m *MapObject) SetType(value string) {
	if m != nil {
		m.Type = &value
	}
}

// 地图地形层结构
type TileLayer struct {
	Type             *string  `protobuf:"bytes,1,req,name=type" json:"type,omitempty"`
	Datas            []uint32 `protobuf:"varint,2,rep,packed,name=datas" json:"datas,omitempty"`
	Objects          [][]byte `protobuf:"bytes,3,rep,name=objects" json:"objects,omitempty"`
	Width            *uint32  `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
	Height           *uint32  `protobuf:"varint,5,opt,name=height" json:"height,omitempty"`
	Name             *string  `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TileLayer) Reset()         { *m = TileLayer{} }
func (m *TileLayer) String() string { return proto.CompactTextString(m) }
func (*TileLayer) ProtoMessage()    {}

func (m *TileLayer) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *TileLayer) GetDatas() []uint32 {
	if m != nil {
		return m.Datas
	}
	return nil
}

func (m *TileLayer) GetObjects() [][]byte {
	if m != nil {
		return m.Objects
	}
	return nil
}

func (m *TileLayer) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *TileLayer) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *TileLayer) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *TileLayer) SetType(value string) {
	if m != nil {
		m.Type = &value
	}
}

func (m *TileLayer) SetDatas(value []uint32) {
	if m != nil {
		m.Datas = value
	}
}

func (m *TileLayer) SetObjects(value [][]byte) {
	if m != nil {
		m.Objects = value
	}
}

func (m *TileLayer) SetWidth(value uint32) {
	if m != nil {
		m.Width = &value
	}
}

func (m *TileLayer) SetHeight(value uint32) {
	if m != nil {
		m.Height = &value
	}
}

func (m *TileLayer) SetName(value string) {
	if m != nil {
		m.Name = &value
	}
}

// 地图数据结构
type TileMap struct {
	Width            *uint32  `protobuf:"varint,1,req,name=width" json:"width,omitempty"`
	Height           *uint32  `protobuf:"varint,2,req,name=height" json:"height,omitempty"`
	Tilewidth        *uint32  `protobuf:"varint,3,req,name=tilewidth" json:"tilewidth,omitempty"`
	Tileheight       *uint32  `protobuf:"varint,4,req,name=tileheight" json:"tileheight,omitempty"`
	Tilesets         [][]byte `protobuf:"bytes,5,rep,name=tilesets" json:"tilesets,omitempty"`
	Layers           [][]byte `protobuf:"bytes,6,rep,name=layers" json:"layers,omitempty"`
	Orientation      *string  `protobuf:"bytes,7,opt,name=orientation,def=isometric" json:"orientation,omitempty"`
	Version          *string  `protobuf:"bytes,8,opt,name=version,def=1.0" json:"version,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *TileMap) Reset()         { *m = TileMap{} }
func (m *TileMap) String() string { return proto.CompactTextString(m) }
func (*TileMap) ProtoMessage()    {}

const Default_TileMap_Orientation string = "isometric"
const Default_TileMap_Version string = "1.0"

func (m *TileMap) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *TileMap) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

func (m *TileMap) GetTilewidth() uint32 {
	if m != nil && m.Tilewidth != nil {
		return *m.Tilewidth
	}
	return 0
}

func (m *TileMap) GetTileheight() uint32 {
	if m != nil && m.Tileheight != nil {
		return *m.Tileheight
	}
	return 0
}

func (m *TileMap) GetTilesets() [][]byte {
	if m != nil {
		return m.Tilesets
	}
	return nil
}

func (m *TileMap) GetLayers() [][]byte {
	if m != nil {
		return m.Layers
	}
	return nil
}

func (m *TileMap) GetOrientation() string {
	if m != nil && m.Orientation != nil {
		return *m.Orientation
	}
	return Default_TileMap_Orientation
}

func (m *TileMap) GetVersion() string {
	if m != nil && m.Version != nil {
		return *m.Version
	}
	return Default_TileMap_Version
}

func (m *TileMap) SetWidth(value uint32) {
	if m != nil {
		m.Width = &value
	}
}

func (m *TileMap) SetHeight(value uint32) {
	if m != nil {
		m.Height = &value
	}
}

func (m *TileMap) SetTilewidth(value uint32) {
	if m != nil {
		m.Tilewidth = &value
	}
}

func (m *TileMap) SetTileheight(value uint32) {
	if m != nil {
		m.Tileheight = &value
	}
}

func (m *TileMap) SetTilesets(value [][]byte) {
	if m != nil {
		m.Tilesets = value
	}
}

func (m *TileMap) SetLayers(value [][]byte) {
	if m != nil {
		m.Layers = value
	}
}

func (m *TileMap) SetOrientation(value string) {
	if m != nil {
		m.Orientation = &value
	}
}

func (m *TileMap) SetVersion(value string) {
	if m != nil {
		m.Version = &value
	}
}

func init() {
}
