// Code generated by protoc-gen-go.
// source: XShare_Logic.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	XShare_Logic.proto

It has these top-level messages:
	StatusInfo
	PlayerBaseInfo
	ItemInfo
	ArmyInfo
	OneBattleAction
	SameTimeBuffEffect
	BattleRound
	BonusInfo
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type OneBattleAction_EBattleActionType int32

const (
	OneBattleAction_eBattleAction_Move   OneBattleAction_EBattleActionType = 1
	OneBattleAction_eBattleAction_Attack OneBattleAction_EBattleActionType = 2
)

var OneBattleAction_EBattleActionType_name = map[int32]string{
	1: "eBattleAction_Move",
	2: "eBattleAction_Attack",
}
var OneBattleAction_EBattleActionType_value = map[string]int32{
	"eBattleAction_Move":   1,
	"eBattleAction_Attack": 2,
}

func (x OneBattleAction_EBattleActionType) Enum() *OneBattleAction_EBattleActionType {
	p := new(OneBattleAction_EBattleActionType)
	*p = x
	return p
}
func (x OneBattleAction_EBattleActionType) String() string {
	return proto.EnumName(OneBattleAction_EBattleActionType_name, int32(x))
}
func (x OneBattleAction_EBattleActionType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *OneBattleAction_EBattleActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OneBattleAction_EBattleActionType_value, data, "OneBattleAction_EBattleActionType")
	if err != nil {
		return err
	}
	*x = OneBattleAction_EBattleActionType(value)
	return nil
}

type StatusInfo struct {
	Name             *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Level            *uint32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	Experience       *uint32 `protobuf:"varint,3,opt,name=experience" json:"experience,omitempty"`
	Gender           *uint32 `protobuf:"varint,4,opt,name=gender" json:"gender,omitempty"`
	HeadIcon         *uint32 `protobuf:"varint,5,opt,name=headIcon" json:"headIcon,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *StatusInfo) Reset()         { *m = StatusInfo{} }
func (m *StatusInfo) String() string { return proto.CompactTextString(m) }
func (*StatusInfo) ProtoMessage()    {}

func (m *StatusInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *StatusInfo) GetLevel() uint32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

func (m *StatusInfo) GetExperience() uint32 {
	if m != nil && m.Experience != nil {
		return *m.Experience
	}
	return 0
}

func (m *StatusInfo) GetGender() uint32 {
	if m != nil && m.Gender != nil {
		return *m.Gender
	}
	return 0
}

func (m *StatusInfo) GetHeadIcon() uint32 {
	if m != nil && m.HeadIcon != nil {
		return *m.HeadIcon
	}
	return 0
}

func (m *StatusInfo) SetName(value string) {
	if m != nil {
		m.Name = &value
	}
}

func (m *StatusInfo) SetLevel(value uint32) {
	if m != nil {
		m.Level = &value
	}
}

func (m *StatusInfo) SetExperience(value uint32) {
	if m != nil {
		m.Experience = &value
	}
}

func (m *StatusInfo) SetGender(value uint32) {
	if m != nil {
		m.Gender = &value
	}
}

func (m *StatusInfo) SetHeadIcon(value uint32) {
	if m != nil {
		m.HeadIcon = &value
	}
}

type PlayerBaseInfo struct {
	Uid              *string     `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Stat             *StatusInfo `protobuf:"bytes,2,req,name=stat" json:"stat,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *PlayerBaseInfo) Reset()         { *m = PlayerBaseInfo{} }
func (m *PlayerBaseInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerBaseInfo) ProtoMessage()    {}

func (m *PlayerBaseInfo) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *PlayerBaseInfo) GetStat() *StatusInfo {
	if m != nil {
		return m.Stat
	}
	return nil
}

func (m *PlayerBaseInfo) SetUid(value string) {
	if m != nil {
		m.Uid = &value
	}
}

func (m *PlayerBaseInfo) SetStat(value *StatusInfo) {
	if m != nil {
		m.Stat = value
	}
}

type ItemInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ItemInfo) Reset()         { *m = ItemInfo{} }
func (m *ItemInfo) String() string { return proto.CompactTextString(m) }
func (*ItemInfo) ProtoMessage()    {}

type ArmyInfo struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ArmyInfo) Reset()         { *m = ArmyInfo{} }
func (m *ArmyInfo) String() string { return proto.CompactTextString(m) }
func (*ArmyInfo) ProtoMessage()    {}

type OneBattleAction struct {
	ActionType       *OneBattleAction_EBattleActionType `protobuf:"varint,1,req,enum=protobuf.OneBattleAction_EBattleActionType" json:"ActionType,omitempty"`
	ActionTarget     *uint32                            `protobuf:"varint,2,req" json:"ActionTarget,omitempty"`
	MainTarget       *uint32                            `protobuf:"varint,3,req" json:"MainTarget,omitempty"`
	AutoHP           *int32                             `protobuf:"varint,4,opt,def=0" json:"AutoHP,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (m *OneBattleAction) Reset()         { *m = OneBattleAction{} }
func (m *OneBattleAction) String() string { return proto.CompactTextString(m) }
func (*OneBattleAction) ProtoMessage()    {}

const Default_OneBattleAction_AutoHP int32 = 0

func (m *OneBattleAction) GetActionType() OneBattleAction_EBattleActionType {
	if m != nil && m.ActionType != nil {
		return *m.ActionType
	}
	return OneBattleAction_eBattleAction_Move
}

func (m *OneBattleAction) GetActionTarget() uint32 {
	if m != nil && m.ActionTarget != nil {
		return *m.ActionTarget
	}
	return 0
}

func (m *OneBattleAction) GetMainTarget() uint32 {
	if m != nil && m.MainTarget != nil {
		return *m.MainTarget
	}
	return 0
}

func (m *OneBattleAction) GetAutoHP() int32 {
	if m != nil && m.AutoHP != nil {
		return *m.AutoHP
	}
	return Default_OneBattleAction_AutoHP
}

func (m *OneBattleAction) SetActionType(value OneBattleAction_EBattleActionType) {
	if m != nil {
		m.ActionType = &value
	}
}

func (m *OneBattleAction) SetActionTarget(value uint32) {
	if m != nil {
		m.ActionTarget = &value
	}
}

func (m *OneBattleAction) SetMainTarget(value uint32) {
	if m != nil {
		m.MainTarget = &value
	}
}

func (m *OneBattleAction) SetAutoHP(value int32) {
	if m != nil {
		m.AutoHP = &value
	}
}

type SameTimeBuffEffect struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SameTimeBuffEffect) Reset()         { *m = SameTimeBuffEffect{} }
func (m *SameTimeBuffEffect) String() string { return proto.CompactTextString(m) }
func (*SameTimeBuffEffect) ProtoMessage()    {}

// 一个回合的表现,
type BattleRound struct {
	Actions          []*OneBattleAction    `protobuf:"bytes,1,rep" json:"Actions,omitempty"`
	BuffEffectArr    []*SameTimeBuffEffect `protobuf:"bytes,2,rep" json:"BuffEffectArr,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *BattleRound) Reset()         { *m = BattleRound{} }
func (m *BattleRound) String() string { return proto.CompactTextString(m) }
func (*BattleRound) ProtoMessage()    {}

func (m *BattleRound) GetActions() []*OneBattleAction {
	if m != nil {
		return m.Actions
	}
	return nil
}

func (m *BattleRound) GetBuffEffectArr() []*SameTimeBuffEffect {
	if m != nil {
		return m.BuffEffectArr
	}
	return nil
}

func (m *BattleRound) SetActions(value []*OneBattleAction) {
	if m != nil {
		m.Actions = value
	}
}

func (m *BattleRound) SetBuffEffectArr(value []*SameTimeBuffEffect) {
	if m != nil {
		m.BuffEffectArr = value
	}
}

type BonusInfo struct {
	BonusExp         *uint32     `protobuf:"varint,1,opt" json:"BonusExp,omitempty"`
	GameMoney        *uint32     `protobuf:"varint,2,opt,def=0" json:"GameMoney,omitempty"`
	RealMoney        *uint32     `protobuf:"varint,3,opt,def=0" json:"RealMoney,omitempty"`
	HonourValue      *uint32     `protobuf:"varint,4,opt" json:"HonourValue,omitempty"`
	ItemList         []*ItemInfo `protobuf:"bytes,5,rep" json:"ItemList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *BonusInfo) Reset()         { *m = BonusInfo{} }
func (m *BonusInfo) String() string { return proto.CompactTextString(m) }
func (*BonusInfo) ProtoMessage()    {}

const Default_BonusInfo_GameMoney uint32 = 0
const Default_BonusInfo_RealMoney uint32 = 0

func (m *BonusInfo) GetBonusExp() uint32 {
	if m != nil && m.BonusExp != nil {
		return *m.BonusExp
	}
	return 0
}

func (m *BonusInfo) GetGameMoney() uint32 {
	if m != nil && m.GameMoney != nil {
		return *m.GameMoney
	}
	return Default_BonusInfo_GameMoney
}

func (m *BonusInfo) GetRealMoney() uint32 {
	if m != nil && m.RealMoney != nil {
		return *m.RealMoney
	}
	return Default_BonusInfo_RealMoney
}

func (m *BonusInfo) GetHonourValue() uint32 {
	if m != nil && m.HonourValue != nil {
		return *m.HonourValue
	}
	return 0
}

func (m *BonusInfo) GetItemList() []*ItemInfo {
	if m != nil {
		return m.ItemList
	}
	return nil
}

func (m *BonusInfo) SetBonusExp(value uint32) {
	if m != nil {
		m.BonusExp = &value
	}
}

func (m *BonusInfo) SetGameMoney(value uint32) {
	if m != nil {
		m.GameMoney = &value
	}
}

func (m *BonusInfo) SetRealMoney(value uint32) {
	if m != nil {
		m.RealMoney = &value
	}
}

func (m *BonusInfo) SetHonourValue(value uint32) {
	if m != nil {
		m.HonourValue = &value
	}
}

func (m *BonusInfo) SetItemList(value []*ItemInfo) {
	if m != nil {
		m.ItemList = value
	}
}

func init() {
	proto.RegisterEnum("protobuf.OneBattleAction_EBattleActionType", OneBattleAction_EBattleActionType_name, OneBattleAction_EBattleActionType_value)
}
