// Code generated by protoc-gen-go.
// source: XShare_Server.proto
// DO NOT EDIT!

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	XShare_Server.proto

It has these top-level messages:
	AccountInfo
*/
package protobuf

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AccountInfo struct {
	Uid              *string `protobuf:"bytes,1,req,name=uid" json:"uid,omitempty"`
	Account          *string `protobuf:"bytes,2,req,name=account" json:"account,omitempty"`
	Password         *string `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	CreateTime       *uint32 `protobuf:"varint,4,opt,name=create_time" json:"create_time,omitempty"`
	Option           *string `protobuf:"bytes,5,opt,name=option" json:"option,omitempty"`
	Language         *uint32 `protobuf:"varint,6,opt,name=language" json:"language,omitempty"`
	Udid             *string `protobuf:"bytes,7,opt,name=udid" json:"udid,omitempty"`
	SessionKey       *string `protobuf:"bytes,8,opt,name=sessionKey" json:"sessionKey,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AccountInfo) Reset()         { *m = AccountInfo{} }
func (m *AccountInfo) String() string { return proto.CompactTextString(m) }
func (*AccountInfo) ProtoMessage()    {}

func (m *AccountInfo) GetUid() string {
	if m != nil && m.Uid != nil {
		return *m.Uid
	}
	return ""
}

func (m *AccountInfo) GetAccount() string {
	if m != nil && m.Account != nil {
		return *m.Account
	}
	return ""
}

func (m *AccountInfo) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *AccountInfo) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *AccountInfo) GetOption() string {
	if m != nil && m.Option != nil {
		return *m.Option
	}
	return ""
}

func (m *AccountInfo) GetLanguage() uint32 {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return 0
}

func (m *AccountInfo) GetUdid() string {
	if m != nil && m.Udid != nil {
		return *m.Udid
	}
	return ""
}

func (m *AccountInfo) GetSessionKey() string {
	if m != nil && m.SessionKey != nil {
		return *m.SessionKey
	}
	return ""
}

func (m *AccountInfo) SetUid(value string) {
	if m != nil {
		m.Uid = &value
	}
}

func (m *AccountInfo) SetAccount(value string) {
	if m != nil {
		m.Account = &value
	}
}

func (m *AccountInfo) SetPassword(value string) {
	if m != nil {
		m.Password = &value
	}
}

func (m *AccountInfo) SetCreateTime(value uint32) {
	if m != nil {
		m.CreateTime = &value
	}
}

func (m *AccountInfo) SetOption(value string) {
	if m != nil {
		m.Option = &value
	}
}

func (m *AccountInfo) SetLanguage(value uint32) {
	if m != nil {
		m.Language = &value
	}
}

func (m *AccountInfo) SetUdid(value string) {
	if m != nil {
		m.Udid = &value
	}
}

func (m *AccountInfo) SetSessionKey(value string) {
	if m != nil {
		m.SessionKey = &value
	}
}

func init() {
}
