-- Generated By protoc-gen-lua Do not Edit
local protobuf = require "protobuf"
module('XShare_Logic_pb')


local STATUSINFO = protobuf.Descriptor();
local STATUSINFO_NAME_FIELD = protobuf.FieldDescriptor();
local STATUSINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
local STATUSINFO_EXPERIENCE_FIELD = protobuf.FieldDescriptor();
local STATUSINFO_GENDER_FIELD = protobuf.FieldDescriptor();
local STATUSINFO_HEADICON_FIELD = protobuf.FieldDescriptor();
local PLAYERBASEINFO = protobuf.Descriptor();
local PLAYERBASEINFO_UID_FIELD = protobuf.FieldDescriptor();
local PLAYERBASEINFO_STAT_FIELD = protobuf.FieldDescriptor();

STATUSINFO_NAME_FIELD.name = "name"
STATUSINFO_NAME_FIELD.full_name = ".protobuf.StatusInfo.name"
STATUSINFO_NAME_FIELD.number = 1
STATUSINFO_NAME_FIELD.index = 0
STATUSINFO_NAME_FIELD.label = 1
STATUSINFO_NAME_FIELD.has_default_value = false
STATUSINFO_NAME_FIELD.default_value = ""
STATUSINFO_NAME_FIELD.type = 9
STATUSINFO_NAME_FIELD.cpp_type = 9

STATUSINFO_LEVEL_FIELD.name = "level"
STATUSINFO_LEVEL_FIELD.full_name = ".protobuf.StatusInfo.level"
STATUSINFO_LEVEL_FIELD.number = 2
STATUSINFO_LEVEL_FIELD.index = 1
STATUSINFO_LEVEL_FIELD.label = 1
STATUSINFO_LEVEL_FIELD.has_default_value = false
STATUSINFO_LEVEL_FIELD.default_value = 0
STATUSINFO_LEVEL_FIELD.type = 13
STATUSINFO_LEVEL_FIELD.cpp_type = 3

STATUSINFO_EXPERIENCE_FIELD.name = "experience"
STATUSINFO_EXPERIENCE_FIELD.full_name = ".protobuf.StatusInfo.experience"
STATUSINFO_EXPERIENCE_FIELD.number = 3
STATUSINFO_EXPERIENCE_FIELD.index = 2
STATUSINFO_EXPERIENCE_FIELD.label = 1
STATUSINFO_EXPERIENCE_FIELD.has_default_value = false
STATUSINFO_EXPERIENCE_FIELD.default_value = 0
STATUSINFO_EXPERIENCE_FIELD.type = 13
STATUSINFO_EXPERIENCE_FIELD.cpp_type = 3

STATUSINFO_GENDER_FIELD.name = "gender"
STATUSINFO_GENDER_FIELD.full_name = ".protobuf.StatusInfo.gender"
STATUSINFO_GENDER_FIELD.number = 4
STATUSINFO_GENDER_FIELD.index = 3
STATUSINFO_GENDER_FIELD.label = 1
STATUSINFO_GENDER_FIELD.has_default_value = false
STATUSINFO_GENDER_FIELD.default_value = 0
STATUSINFO_GENDER_FIELD.type = 13
STATUSINFO_GENDER_FIELD.cpp_type = 3

STATUSINFO_HEADICON_FIELD.name = "headIcon"
STATUSINFO_HEADICON_FIELD.full_name = ".protobuf.StatusInfo.headIcon"
STATUSINFO_HEADICON_FIELD.number = 5
STATUSINFO_HEADICON_FIELD.index = 4
STATUSINFO_HEADICON_FIELD.label = 1
STATUSINFO_HEADICON_FIELD.has_default_value = false
STATUSINFO_HEADICON_FIELD.default_value = 0
STATUSINFO_HEADICON_FIELD.type = 13
STATUSINFO_HEADICON_FIELD.cpp_type = 3

STATUSINFO.name = "StatusInfo"
STATUSINFO.full_name = ".protobuf.StatusInfo"
STATUSINFO.nested_types = {}
STATUSINFO.enum_types = {}
STATUSINFO.fields = {STATUSINFO_NAME_FIELD, STATUSINFO_LEVEL_FIELD, STATUSINFO_EXPERIENCE_FIELD, STATUSINFO_GENDER_FIELD, STATUSINFO_HEADICON_FIELD}
STATUSINFO.is_extendable = false
STATUSINFO.extensions = {}
PLAYERBASEINFO_UID_FIELD.name = "uid"
PLAYERBASEINFO_UID_FIELD.full_name = ".protobuf.PlayerBaseInfo.uid"
PLAYERBASEINFO_UID_FIELD.number = 1
PLAYERBASEINFO_UID_FIELD.index = 0
PLAYERBASEINFO_UID_FIELD.label = 2
PLAYERBASEINFO_UID_FIELD.has_default_value = false
PLAYERBASEINFO_UID_FIELD.default_value = ""
PLAYERBASEINFO_UID_FIELD.type = 9
PLAYERBASEINFO_UID_FIELD.cpp_type = 9

PLAYERBASEINFO_STAT_FIELD.name = "stat"
PLAYERBASEINFO_STAT_FIELD.full_name = ".protobuf.PlayerBaseInfo.stat"
PLAYERBASEINFO_STAT_FIELD.number = 2
PLAYERBASEINFO_STAT_FIELD.index = 1
PLAYERBASEINFO_STAT_FIELD.label = 2
PLAYERBASEINFO_STAT_FIELD.has_default_value = false
PLAYERBASEINFO_STAT_FIELD.default_value = nil
PLAYERBASEINFO_STAT_FIELD.message_type = STATUSINFO
PLAYERBASEINFO_STAT_FIELD.type = 11
PLAYERBASEINFO_STAT_FIELD.cpp_type = 10

PLAYERBASEINFO.name = "PlayerBaseInfo"
PLAYERBASEINFO.full_name = ".protobuf.PlayerBaseInfo"
PLAYERBASEINFO.nested_types = {}
PLAYERBASEINFO.enum_types = {}
PLAYERBASEINFO.fields = {PLAYERBASEINFO_UID_FIELD, PLAYERBASEINFO_STAT_FIELD}
PLAYERBASEINFO.is_extendable = false
PLAYERBASEINFO.extensions = {}

PlayerBaseInfo = protobuf.Message(PLAYERBASEINFO)
StatusInfo = protobuf.Message(STATUSINFO)

